version: 2
project_name: agentsh

before:
  hooks:
    - go mod download
    - ./scripts/build-envshim.sh

builds:
  - id: agentsh-linux
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: agentsh-darwin
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  # Windows build disabled - project has Unix-only deps (go-fuse, pty, shim)
  # Platform package exists in internal/platform/windows/ for future use

  - id: shim-linux
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: shim-darwin
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: agentsh-linux
    ids:
      - agentsh-linux
      - shim-linux
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml
      - build/envshim/linux_{{ .Arch }}/libenvshim.so

  - id: agentsh-darwin
    ids:
      - agentsh-darwin
      - shim-darwin
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: agentsh
    package_name: agentsh
    ids:
      - agentsh-linux
      - shim-linux
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    vendor: AgentSH
    homepage: https://github.com/agentsh/agentsh
    maintainer: AgentSH Team <team@agentsh.dev>
    description: |
      Secure sandboxed shell for AI agents.
      Provides policy-based access control for file, network, and command operations.
    license: MIT
    section: utils
    priority: optional
    contents:
      # Configuration
      - src: packaging/config.yaml
        dst: /etc/agentsh/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
      # Shell completions
      - src: packaging/completions/agentsh.bash
        dst: /usr/share/bash-completion/completions/agentsh
        file_info:
          mode: 0644
      - src: packaging/completions/agentsh.zsh
        dst: /usr/share/zsh/site-functions/_agentsh
        file_info:
          mode: 0644
      - src: packaging/completions/agentsh.fish
        dst: /usr/share/fish/vendor_completions.d/agentsh.fish
        file_info:
          mode: 0644
      # Documentation
      - src: README.md
        dst: /usr/share/doc/agentsh/README.md
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/agentsh/LICENSE
        file_info:
          mode: 0644
      # Envshim library (Linux only)
      - src: build/envshim/linux_{{ .Arch }}/libenvshim.so
        dst: /usr/lib/agentsh/libenvshim.so
        file_info:
          mode: 0644
      # Create directories
      - dst: /etc/agentsh
        type: dir
        file_info:
          mode: 0755
      - dst: /usr/lib/agentsh
        type: dir
        file_info:
          mode: 0755
    rpm:
      group: Applications/System
    archlinux:
      pkgbase: agentsh

release:
  draft: false
  prerelease: auto
