version: 2
project_name: agentsh

before:
  hooks:
    - go mod download
    - ./scripts/build-envshim.sh

builds:
  - id: agentsh-linux
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: agentsh-darwin
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: agentsh-windows
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: shim-linux
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: shim-darwin
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  # unixwrap: seccomp wrapper for Linux (requires CGO + libseccomp)
  # Only building amd64 - arm64 cross-compilation requires libseccomp-dev:arm64
  # which is complex to set up in CI. arm64 users get graceful degradation.
  - id: unixwrap-linux-amd64
    main: ./cmd/agentsh-unixwrap
    binary: agentsh-unixwrap
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

  # macwrap: XPC sandbox wrapper for macOS (requires CGO)
  # NOTE: This build requires macOS with Xcode to compile - SKIPPED in CI
  # Build locally with: CGO_ENABLED=1 go build -o bin/agentsh-macwrap ./cmd/agentsh-macwrap
  # - id: macwrap-darwin
  #   main: ./cmd/agentsh-macwrap
  #   binary: agentsh-macwrap
  #   env:
  #     - CGO_ENABLED=1
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #     - arm64
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

archives:
  - id: agentsh-linux-amd64
    ids:
      - agentsh-linux
      - shim-linux
      - unixwrap-linux-amd64
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml
      - src: build/envshim/linux_amd64/*
        dst: .
        strip_parent: true
    builds_info:
      mode: 0755
      group: root
      owner: root

  - id: agentsh-linux-arm64
    ids:
      - agentsh-linux
      - shim-linux
      # unixwrap not available for arm64 - users get graceful degradation
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml
      - src: build/envshim/linux_arm64/*
        dst: .
        strip_parent: true
    builds_info:
      mode: 0755
      group: root
      owner: root

  - id: agentsh-darwin
    ids:
      - agentsh-darwin
      - shim-darwin
      # macwrap-darwin excluded - requires native macOS build
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml

  - id: agentsh-windows
    ids:
      - agentsh-windows
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: agentsh
    package_name: agentsh
    ids:
      - agentsh-linux
      - shim-linux
      - unixwrap-linux-amd64
      # unixwrap not available for arm64 - users get graceful degradation
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    vendor: AgentSH
    homepage: https://github.com/agentsh/agentsh
    maintainer: AgentSH Team <team@agentsh.dev>
    description: |
      Secure sandboxed shell for AI agents.
      Provides policy-based access control for file, network, and command operations.
    license: MIT
    section: utils
    priority: optional
    contents:
      # Configuration
      - src: packaging/config.yaml
        dst: /etc/agentsh/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
      # Shell completions
      - src: packaging/completions/agentsh.bash
        dst: /usr/share/bash-completion/completions/agentsh
        file_info:
          mode: 0644
      - src: packaging/completions/agentsh.zsh
        dst: /usr/share/zsh/site-functions/_agentsh
        file_info:
          mode: 0644
      - src: packaging/completions/agentsh.fish
        dst: /usr/share/fish/vendor_completions.d/agentsh.fish
        file_info:
          mode: 0644
      # Documentation
      - src: README.md
        dst: /usr/share/doc/agentsh/README.md
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/agentsh/LICENSE
        file_info:
          mode: 0644
      # Envshim library (Linux only) - uses glob to skip if not built
      - src: build/envshim/linux_{{ .Arch }}/*.so
        dst: /usr/lib/agentsh/
      # Create directories
      - dst: /etc/agentsh
        type: dir
        file_info:
          mode: 0755
      - dst: /usr/lib/agentsh
        type: dir
        file_info:
          mode: 0755
    rpm:
      group: Applications/System
    archlinux:
      pkgbase: agentsh

release:
  draft: false
  prerelease: auto

homebrew_casks:
  - name: agentsh
    ids:
      - agentsh-darwin
      - shim-darwin
      # macwrap-darwin excluded - requires native macOS build
    # Repository to push the cask to
    repository:
      owner: agentsh
      name: homebrew-tap
      branch: main
      # Use index to safely get env var (empty string if not set)
      token: '{{ index .Env "HOMEBREW_TAP_GITHUB_TOKEN" }}'
    # Skip if no token (allows local builds without pushing)
    skip_upload: true  # Temporarily disabled - no homebrew tap set up yet
    # Cask metadata
    homepage: "https://github.com/agentsh/agentsh"
    description: "Secure sandboxed shell for AI agents"
    # Binaries to symlink
    binaries:
      - agentsh
      - agentsh-shell-shim
      # agentsh-macwrap excluded - requires native macOS build
    # Post-install hook to remove quarantine (unsigned binary)
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr",
            args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    # Caveats shown after installation
    caveats: |
      To start using agentsh:
        agentsh server &
        agentsh session create --workspace .

      To create a config file:
        mkdir -p /usr/local/etc/agentsh
        agentsh config init > /usr/local/etc/agentsh/config.yaml

