version: 2
project_name: agentsh

before:
  hooks:
    - go mod download
    - ./scripts/build-envshim.sh

builds:
  - id: agentsh-linux
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: agentsh-darwin
    main: ./cmd/agentsh
    binary: agentsh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

  - id: shim-linux
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - id: shim-darwin
    main: ./cmd/agentsh-shell-shim
    binary: agentsh-shell-shim
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: agentsh-linux
    ids:
      - agentsh-linux
      - shim-linux
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml
      - build/envshim/linux_{{ .Arch }}/libenvshim.so

  - id: agentsh-darwin
    ids:
      - agentsh-darwin
      - shim-darwin
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yml
      - default-policy.yml

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: agentsh
    package_name: agentsh
    ids:
      - agentsh-linux
      - shim-linux
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    homepage: https://github.com/agentsh/agentsh
    maintainer: agentsh maintainers <maintainers@example.com>
    description: Secure agent shell (agentsh) and a shell shim for container compatibility.
    license: Apache-2.0
    contents:
      - src: config.yml
        dst: /etc/agentsh/config.yaml
        type: config
      - src: default-policy.yml
        dst: /etc/agentsh/default-policy.yml
        type: config
      - src: build/envshim/linux_amd64/libenvshim.so
        dst: /usr/lib/agentsh/libenvshim.so
        file_info:
          mode: 0644
    # Important: packages do NOT replace /bin/sh automatically. Use the explicit shim installer:
    #   agentsh shim install-shell --root / --shim /usr/bin/agentsh-shell-shim --i-understand-this-modifies-the-host

release:
  draft: false
  prerelease: auto
