package cli

import (
	"bytes"
	"strings"
	"testing"
)

func TestDetectCmd_Table(t *testing.T) {
	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "Platform:") {
		t.Error("output missing Platform")
	}
	if !strings.Contains(output, "Security Mode:") {
		t.Error("output missing Security Mode")
	}
}

func TestDetectCmd_JSON(t *testing.T) {
	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{"--output", "json"})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	output := buf.String()
	if !strings.HasPrefix(output, "{") {
		t.Error("JSON output should start with {")
	}
	if !strings.Contains(output, `"platform"`) {
		t.Error("JSON output missing platform field")
	}
}

func TestDetectCmd_YAML(t *testing.T) {
	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{"--output", "yaml"})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "platform:") {
		t.Error("YAML output missing platform field")
	}
}

func TestDetectConfigCmd(t *testing.T) {
	cmd := newDetectCmd()
	buf := new(bytes.Buffer)
	cmd.SetOut(buf)
	cmd.SetErr(buf)
	cmd.SetArgs([]string{"config"})

	err := cmd.Execute()
	if err != nil {
		t.Fatalf("Execute() error: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "Generated by: agentsh detect config") {
		t.Error("config output missing header")
	}
	if !strings.Contains(output, "security:") {
		t.Error("config output missing security section")
	}
}
