// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: canyonroad/wtp/v1/wtp.proto

package wtpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_ZSTD        Compression = 2
	Compression_COMPRESSION_GZIP        Compression = 3
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_ZSTD",
		3: "COMPRESSION_GZIP",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_ZSTD":        2,
		"COMPRESSION_GZIP":        3,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_canyonroad_wtp_v1_wtp_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_canyonroad_wtp_v1_wtp_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{0}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_SessionInit
	//	*ClientMessage_SessionUpdate
	//	*ClientMessage_EventBatch
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_TransportLoss
	//	*ClientMessage_Shutdown
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetSessionInit() *SessionInit {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_SessionInit); ok {
			return x.SessionInit
		}
	}
	return nil
}

func (x *ClientMessage) GetSessionUpdate() *SessionUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_SessionUpdate); ok {
			return x.SessionUpdate
		}
	}
	return nil
}

func (x *ClientMessage) GetEventBatch() *EventBatch {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_EventBatch); ok {
			return x.EventBatch
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetTransportLoss() *TransportLoss {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_TransportLoss); ok {
			return x.TransportLoss
		}
	}
	return nil
}

func (x *ClientMessage) GetShutdown() *ClientShutdown {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_SessionInit struct {
	SessionInit *SessionInit `protobuf:"bytes,1,opt,name=session_init,json=sessionInit,proto3,oneof"`
}

type ClientMessage_SessionUpdate struct {
	SessionUpdate *SessionUpdate `protobuf:"bytes,2,opt,name=session_update,json=sessionUpdate,proto3,oneof"`
}

type ClientMessage_EventBatch struct {
	EventBatch *EventBatch `protobuf:"bytes,3,opt,name=event_batch,json=eventBatch,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_TransportLoss struct {
	TransportLoss *TransportLoss `protobuf:"bytes,5,opt,name=transport_loss,json=transportLoss,proto3,oneof"`
}

type ClientMessage_Shutdown struct {
	Shutdown *ClientShutdown `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

func (*ClientMessage_SessionInit) isClientMessage_Msg() {}

func (*ClientMessage_SessionUpdate) isClientMessage_Msg() {}

func (*ClientMessage_EventBatch) isClientMessage_Msg() {}

func (*ClientMessage_Heartbeat) isClientMessage_Msg() {}

func (*ClientMessage_TransportLoss) isClientMessage_Msg() {}

func (*ClientMessage_Shutdown) isClientMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_SessionAck
	//	*ServerMessage_BatchAck
	//	*ServerMessage_ServerHeartbeat
	//	*ServerMessage_Goaway
	//	*ServerMessage_ServerUpdate
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetSessionAck() *SessionAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_SessionAck); ok {
			return x.SessionAck
		}
	}
	return nil
}

func (x *ServerMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *ServerMessage) GetServerHeartbeat() *ServerHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ServerHeartbeat); ok {
			return x.ServerHeartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetGoaway() *Goaway {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Goaway); ok {
			return x.Goaway
		}
	}
	return nil
}

func (x *ServerMessage) GetServerUpdate() *SessionUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ServerUpdate); ok {
			return x.ServerUpdate
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_SessionAck struct {
	SessionAck *SessionAck `protobuf:"bytes,1,opt,name=session_ack,json=sessionAck,proto3,oneof"`
}

type ServerMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,2,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type ServerMessage_ServerHeartbeat struct {
	ServerHeartbeat *ServerHeartbeat `protobuf:"bytes,3,opt,name=server_heartbeat,json=serverHeartbeat,proto3,oneof"`
}

type ServerMessage_Goaway struct {
	Goaway *Goaway `protobuf:"bytes,4,opt,name=goaway,proto3,oneof"`
}

type ServerMessage_ServerUpdate struct {
	ServerUpdate *SessionUpdate `protobuf:"bytes,5,opt,name=server_update,json=serverUpdate,proto3,oneof"`
}

func (*ServerMessage_SessionAck) isServerMessage_Msg() {}

func (*ServerMessage_BatchAck) isServerMessage_Msg() {}

func (*ServerMessage_ServerHeartbeat) isServerMessage_Msg() {}

func (*ServerMessage_Goaway) isServerMessage_Msg() {}

func (*ServerMessage_ServerUpdate) isServerMessage_Msg() {}

// SessionInit (§7.1)
type SessionInit struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OcsfVersion         string                 `protobuf:"bytes,2,opt,name=ocsf_version,json=ocsfVersion,proto3" json:"ocsf_version,omitempty"`
	FormatVersion       uint32                 `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Algorithm           string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // hmac-sha256 | hmac-sha512
	KeyFingerprint      string                 `protobuf:"bytes,5,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	ContextDigest       string                 `protobuf:"bytes,6,opt,name=context_digest,json=contextDigest,proto3" json:"context_digest,omitempty"` // hex-encoded SHA-256
	WalHighWatermarkSeq uint64                 `protobuf:"varint,7,opt,name=wal_high_watermark_seq,json=walHighWatermarkSeq,proto3" json:"wal_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,8,opt,name=generation,proto3" json:"generation,omitempty"`
	AgentId             string                 `protobuf:"bytes,9,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion        string                 `protobuf:"bytes,10,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	TotalChained        uint64                 `protobuf:"varint,11,opt,name=total_chained,json=totalChained,proto3" json:"total_chained,omitempty"` // count of records sink has chained
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionInit) Reset() {
	*x = SessionInit{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInit) ProtoMessage() {}

func (x *SessionInit) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInit.ProtoReflect.Descriptor instead.
func (*SessionInit) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInit) GetOcsfVersion() string {
	if x != nil {
		return x.OcsfVersion
	}
	return ""
}

func (x *SessionInit) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SessionInit) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SessionInit) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *SessionInit) GetContextDigest() string {
	if x != nil {
		return x.ContextDigest
	}
	return ""
}

func (x *SessionInit) GetWalHighWatermarkSeq() uint64 {
	if x != nil {
		return x.WalHighWatermarkSeq
	}
	return 0
}

func (x *SessionInit) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionInit) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionInit) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SessionInit) GetTotalChained() uint64 {
	if x != nil {
		return x.TotalChained
	}
	return 0
}

type SessionAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Accepted            bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason        string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // empty when accepted=true
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionAck) Reset() {
	*x = SessionAck{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAck) ProtoMessage() {}

func (x *SessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAck.ProtoReflect.Descriptor instead.
func (*SessionAck) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{3}
}

func (x *SessionAck) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

func (x *SessionAck) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// SessionUpdate (§7.2): generation roll, key rotation, context change.
type SessionUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewGeneration     uint32                 `protobuf:"varint,1,opt,name=new_generation,json=newGeneration,proto3" json:"new_generation,omitempty"`
	NewKeyFingerprint string                 `protobuf:"bytes,2,opt,name=new_key_fingerprint,json=newKeyFingerprint,proto3" json:"new_key_fingerprint,omitempty"`
	NewContextDigest  string                 `protobuf:"bytes,3,opt,name=new_context_digest,json=newContextDigest,proto3" json:"new_context_digest,omitempty"`
	BoundarySequence  uint64                 `protobuf:"varint,4,opt,name=boundary_sequence,json=boundarySequence,proto3" json:"boundary_sequence,omitempty"` // last seq of prior generation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionUpdate) Reset() {
	*x = SessionUpdate{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdate) ProtoMessage() {}

func (x *SessionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdate.ProtoReflect.Descriptor instead.
func (*SessionUpdate) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{4}
}

func (x *SessionUpdate) GetNewGeneration() uint32 {
	if x != nil {
		return x.NewGeneration
	}
	return 0
}

func (x *SessionUpdate) GetNewKeyFingerprint() string {
	if x != nil {
		return x.NewKeyFingerprint
	}
	return ""
}

func (x *SessionUpdate) GetNewContextDigest() string {
	if x != nil {
		return x.NewContextDigest
	}
	return ""
}

func (x *SessionUpdate) GetBoundarySequence() uint64 {
	if x != nil {
		return x.BoundarySequence
	}
	return 0
}

// EventBatch (§7.3)
type EventBatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromSequence      uint64                 `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	ToSequence        uint64                 `protobuf:"varint,2,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`
	Generation        uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Events            []*CompactEvent        `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	Compression       Compression            `protobuf:"varint,5,opt,name=compression,proto3,enum=canyonroad.wtp.v1.Compression" json:"compression,omitempty"`
	CompressedPayload []byte                 `protobuf:"bytes,6,opt,name=compressed_payload,json=compressedPayload,proto3" json:"compressed_payload,omitempty"` // when compression != NONE; events repeated empty
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{5}
}

func (x *EventBatch) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *EventBatch) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

func (x *EventBatch) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventBatch) GetEvents() []*CompactEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *EventBatch) GetCompressedPayload() []byte {
	if x != nil {
		return x.CompressedPayload
	}
	return nil
}

// CompactEvent (§6.3)
type CompactEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sequence           uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Generation         uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	TimestampUnixNanos uint64                 `protobuf:"varint,3,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	OcsfClassUid       uint32                 `protobuf:"varint,4,opt,name=ocsf_class_uid,json=ocsfClassUid,proto3" json:"ocsf_class_uid,omitempty"`
	OcsfActivityId     uint32                 `protobuf:"varint,5,opt,name=ocsf_activity_id,json=ocsfActivityId,proto3" json:"ocsf_activity_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // protobuf-encoded class-specific payload
	Integrity          *IntegrityRecord       `protobuf:"bytes,7,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompactEvent) Reset() {
	*x = CompactEvent{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactEvent) ProtoMessage() {}

func (x *CompactEvent) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactEvent.ProtoReflect.Descriptor instead.
func (*CompactEvent) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{6}
}

func (x *CompactEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CompactEvent) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *CompactEvent) GetTimestampUnixNanos() uint64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *CompactEvent) GetOcsfClassUid() uint32 {
	if x != nil {
		return x.OcsfClassUid
	}
	return 0
}

func (x *CompactEvent) GetOcsfActivityId() uint32 {
	if x != nil {
		return x.OcsfActivityId
	}
	return 0
}

func (x *CompactEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CompactEvent) GetIntegrity() *IntegrityRecord {
	if x != nil {
		return x.Integrity
	}
	return nil
}

type IntegrityRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion  uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Generation     uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	PrevHash       string                 `protobuf:"bytes,4,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	EventHash      string                 `protobuf:"bytes,5,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	ContextDigest  string                 `protobuf:"bytes,6,opt,name=context_digest,json=contextDigest,proto3" json:"context_digest,omitempty"`
	KeyFingerprint string                 `protobuf:"bytes,7,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntegrityRecord) Reset() {
	*x = IntegrityRecord{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityRecord) ProtoMessage() {}

func (x *IntegrityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityRecord.ProtoReflect.Descriptor instead.
func (*IntegrityRecord) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{7}
}

func (x *IntegrityRecord) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *IntegrityRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *IntegrityRecord) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *IntegrityRecord) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *IntegrityRecord) GetEventHash() string {
	if x != nil {
		return x.EventHash
	}
	return ""
}

func (x *IntegrityRecord) GetContextDigest() string {
	if x != nil {
		return x.ContextDigest
	}
	return ""
}

func (x *IntegrityRecord) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

type Heartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WalHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=wal_high_watermark_seq,json=walHighWatermarkSeq,proto3" json:"wal_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetWalHighWatermarkSeq() uint64 {
	if x != nil {
		return x.WalHighWatermarkSeq
	}
	return 0
}

func (x *Heartbeat) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type ServerHeartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerHeartbeat) Reset() {
	*x = ServerHeartbeat{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeat) ProtoMessage() {}

func (x *ServerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeat.ProtoReflect.Descriptor instead.
func (*ServerHeartbeat) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{9}
}

func (x *ServerHeartbeat) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

type BatchAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AckHighWatermarkSeq uint64                 `protobuf:"varint,1,opt,name=ack_high_watermark_seq,json=ackHighWatermarkSeq,proto3" json:"ack_high_watermark_seq,omitempty"`
	Generation          uint32                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{10}
}

func (x *BatchAck) GetAckHighWatermarkSeq() uint64 {
	if x != nil {
		return x.AckHighWatermarkSeq
	}
	return 0
}

func (x *BatchAck) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// TransportLoss (§7.5) — emitted on WAL overflow or CRC corruption.
type TransportLoss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSequence  uint64                 `protobuf:"varint,1,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	ToSequence    uint64                 `protobuf:"varint,2,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`
	Generation    uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // "overflow" | "crc_corruption"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportLoss) Reset() {
	*x = TransportLoss{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportLoss) ProtoMessage() {}

func (x *TransportLoss) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportLoss.ProtoReflect.Descriptor instead.
func (*TransportLoss) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{11}
}

func (x *TransportLoss) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *TransportLoss) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

func (x *TransportLoss) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TransportLoss) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Goaway struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // "DRAINING" | "OVERLOAD" | etc.
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RetryImmediately bool                   `protobuf:"varint,3,opt,name=retry_immediately,json=retryImmediately,proto3" json:"retry_immediately,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Goaway) Reset() {
	*x = Goaway{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goaway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goaway) ProtoMessage() {}

func (x *Goaway) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goaway.ProtoReflect.Descriptor instead.
func (*Goaway) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{12}
}

func (x *Goaway) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Goaway) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Goaway) GetRetryImmediately() bool {
	if x != nil {
		return x.RetryImmediately
	}
	return false
}

type ClientShutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientShutdown) Reset() {
	*x = ClientShutdown{}
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientShutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientShutdown) ProtoMessage() {}

func (x *ClientShutdown) ProtoReflect() protoreflect.Message {
	mi := &file_canyonroad_wtp_v1_wtp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientShutdown.ProtoReflect.Descriptor instead.
func (*ClientShutdown) Descriptor() ([]byte, []int) {
	return file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP(), []int{13}
}

func (x *ClientShutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_canyonroad_wtp_v1_wtp_proto protoreflect.FileDescriptor

const file_canyonroad_wtp_v1_wtp_proto_rawDesc = "" +
	"\n" +
	"\x1bcanyonroad/wtp/v1/wtp.proto\x12\x11canyonroad.wtp.v1\"\xb2\x03\n" +
	"\rClientMessage\x12C\n" +
	"\fsession_init\x18\x01 \x01(\v2\x1e.canyonroad.wtp.v1.SessionInitH\x00R\vsessionInit\x12I\n" +
	"\x0esession_update\x18\x02 \x01(\v2 .canyonroad.wtp.v1.SessionUpdateH\x00R\rsessionUpdate\x12@\n" +
	"\vevent_batch\x18\x03 \x01(\v2\x1d.canyonroad.wtp.v1.EventBatchH\x00R\n" +
	"eventBatch\x12<\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1c.canyonroad.wtp.v1.HeartbeatH\x00R\theartbeat\x12I\n" +
	"\x0etransport_loss\x18\x05 \x01(\v2 .canyonroad.wtp.v1.TransportLossH\x00R\rtransportLoss\x12?\n" +
	"\bshutdown\x18\x06 \x01(\v2!.canyonroad.wtp.v1.ClientShutdownH\x00R\bshutdownB\x05\n" +
	"\x03msg\"\xe3\x02\n" +
	"\rServerMessage\x12@\n" +
	"\vsession_ack\x18\x01 \x01(\v2\x1d.canyonroad.wtp.v1.SessionAckH\x00R\n" +
	"sessionAck\x12:\n" +
	"\tbatch_ack\x18\x02 \x01(\v2\x1b.canyonroad.wtp.v1.BatchAckH\x00R\bbatchAck\x12O\n" +
	"\x10server_heartbeat\x18\x03 \x01(\v2\".canyonroad.wtp.v1.ServerHeartbeatH\x00R\x0fserverHeartbeat\x123\n" +
	"\x06goaway\x18\x04 \x01(\v2\x19.canyonroad.wtp.v1.GoawayH\x00R\x06goaway\x12G\n" +
	"\rserver_update\x18\x05 \x01(\v2 .canyonroad.wtp.v1.SessionUpdateH\x00R\fserverUpdateB\x05\n" +
	"\x03msg\"\x9e\x03\n" +
	"\vSessionInit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\focsf_version\x18\x02 \x01(\tR\vocsfVersion\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\rR\rformatVersion\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12'\n" +
	"\x0fkey_fingerprint\x18\x05 \x01(\tR\x0ekeyFingerprint\x12%\n" +
	"\x0econtext_digest\x18\x06 \x01(\tR\rcontextDigest\x123\n" +
	"\x16wal_high_watermark_seq\x18\a \x01(\x04R\x13walHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\b \x01(\rR\n" +
	"generation\x12\x19\n" +
	"\bagent_id\x18\t \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\n" +
	" \x01(\tR\fagentVersion\x12#\n" +
	"\rtotal_chained\x18\v \x01(\x04R\ftotalChained\"\xa2\x01\n" +
	"\n" +
	"SessionAck\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"\xc1\x01\n" +
	"\rSessionUpdate\x12%\n" +
	"\x0enew_generation\x18\x01 \x01(\rR\rnewGeneration\x12.\n" +
	"\x13new_key_fingerprint\x18\x02 \x01(\tR\x11newKeyFingerprint\x12,\n" +
	"\x12new_context_digest\x18\x03 \x01(\tR\x10newContextDigest\x12+\n" +
	"\x11boundary_sequence\x18\x04 \x01(\x04R\x10boundarySequence\"\x9c\x02\n" +
	"\n" +
	"EventBatch\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vto_sequence\x18\x02 \x01(\x04R\n" +
	"toSequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x127\n" +
	"\x06events\x18\x04 \x03(\v2\x1f.canyonroad.wtp.v1.CompactEventR\x06events\x12@\n" +
	"\vcompression\x18\x05 \x01(\x0e2\x1e.canyonroad.wtp.v1.CompressionR\vcompression\x12-\n" +
	"\x12compressed_payload\x18\x06 \x01(\fR\x11compressedPayload\"\xa8\x02\n" +
	"\fCompactEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\x120\n" +
	"\x14timestamp_unix_nanos\x18\x03 \x01(\x04R\x12timestampUnixNanos\x12$\n" +
	"\x0eocsf_class_uid\x18\x04 \x01(\rR\focsfClassUid\x12(\n" +
	"\x10ocsf_activity_id\x18\x05 \x01(\rR\x0eocsfActivityId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12@\n" +
	"\tintegrity\x18\a \x01(\v2\".canyonroad.wtp.v1.IntegrityRecordR\tintegrity\"\x80\x02\n" +
	"\x0fIntegrityRecord\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12\x1b\n" +
	"\tprev_hash\x18\x04 \x01(\tR\bprevHash\x12\x1d\n" +
	"\n" +
	"event_hash\x18\x05 \x01(\tR\teventHash\x12%\n" +
	"\x0econtext_digest\x18\x06 \x01(\tR\rcontextDigest\x12'\n" +
	"\x0fkey_fingerprint\x18\a \x01(\tR\x0ekeyFingerprint\"`\n" +
	"\tHeartbeat\x123\n" +
	"\x16wal_high_watermark_seq\x18\x01 \x01(\x04R\x13walHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\"F\n" +
	"\x0fServerHeartbeat\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\"_\n" +
	"\bBatchAck\x123\n" +
	"\x16ack_high_watermark_seq\x18\x01 \x01(\x04R\x13ackHighWatermarkSeq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\rR\n" +
	"generation\"\x8d\x01\n" +
	"\rTransportLoss\x12#\n" +
	"\rfrom_sequence\x18\x01 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vto_sequence\x18\x02 \x01(\x04R\n" +
	"toSequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x06Goaway\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11retry_immediately\x18\x03 \x01(\bR\x10retryImmediately\"(\n" +
	"\x0eClientShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*l\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x02\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x032^\n" +
	"\n" +
	"Watchtower\x12P\n" +
	"\x06Stream\x12 .canyonroad.wtp.v1.ClientMessage\x1a .canyonroad.wtp.v1.ServerMessage(\x010\x01B:Z8github.com/agentsh/agentsh/proto/canyonroad/wtp/v1;wtpv1b\x06proto3"

var (
	file_canyonroad_wtp_v1_wtp_proto_rawDescOnce sync.Once
	file_canyonroad_wtp_v1_wtp_proto_rawDescData []byte
)

func file_canyonroad_wtp_v1_wtp_proto_rawDescGZIP() []byte {
	file_canyonroad_wtp_v1_wtp_proto_rawDescOnce.Do(func() {
		file_canyonroad_wtp_v1_wtp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_canyonroad_wtp_v1_wtp_proto_rawDesc), len(file_canyonroad_wtp_v1_wtp_proto_rawDesc)))
	})
	return file_canyonroad_wtp_v1_wtp_proto_rawDescData
}

var file_canyonroad_wtp_v1_wtp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_canyonroad_wtp_v1_wtp_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_canyonroad_wtp_v1_wtp_proto_goTypes = []any{
	(Compression)(0),        // 0: canyonroad.wtp.v1.Compression
	(*ClientMessage)(nil),   // 1: canyonroad.wtp.v1.ClientMessage
	(*ServerMessage)(nil),   // 2: canyonroad.wtp.v1.ServerMessage
	(*SessionInit)(nil),     // 3: canyonroad.wtp.v1.SessionInit
	(*SessionAck)(nil),      // 4: canyonroad.wtp.v1.SessionAck
	(*SessionUpdate)(nil),   // 5: canyonroad.wtp.v1.SessionUpdate
	(*EventBatch)(nil),      // 6: canyonroad.wtp.v1.EventBatch
	(*CompactEvent)(nil),    // 7: canyonroad.wtp.v1.CompactEvent
	(*IntegrityRecord)(nil), // 8: canyonroad.wtp.v1.IntegrityRecord
	(*Heartbeat)(nil),       // 9: canyonroad.wtp.v1.Heartbeat
	(*ServerHeartbeat)(nil), // 10: canyonroad.wtp.v1.ServerHeartbeat
	(*BatchAck)(nil),        // 11: canyonroad.wtp.v1.BatchAck
	(*TransportLoss)(nil),   // 12: canyonroad.wtp.v1.TransportLoss
	(*Goaway)(nil),          // 13: canyonroad.wtp.v1.Goaway
	(*ClientShutdown)(nil),  // 14: canyonroad.wtp.v1.ClientShutdown
}
var file_canyonroad_wtp_v1_wtp_proto_depIdxs = []int32{
	3,  // 0: canyonroad.wtp.v1.ClientMessage.session_init:type_name -> canyonroad.wtp.v1.SessionInit
	5,  // 1: canyonroad.wtp.v1.ClientMessage.session_update:type_name -> canyonroad.wtp.v1.SessionUpdate
	6,  // 2: canyonroad.wtp.v1.ClientMessage.event_batch:type_name -> canyonroad.wtp.v1.EventBatch
	9,  // 3: canyonroad.wtp.v1.ClientMessage.heartbeat:type_name -> canyonroad.wtp.v1.Heartbeat
	12, // 4: canyonroad.wtp.v1.ClientMessage.transport_loss:type_name -> canyonroad.wtp.v1.TransportLoss
	14, // 5: canyonroad.wtp.v1.ClientMessage.shutdown:type_name -> canyonroad.wtp.v1.ClientShutdown
	4,  // 6: canyonroad.wtp.v1.ServerMessage.session_ack:type_name -> canyonroad.wtp.v1.SessionAck
	11, // 7: canyonroad.wtp.v1.ServerMessage.batch_ack:type_name -> canyonroad.wtp.v1.BatchAck
	10, // 8: canyonroad.wtp.v1.ServerMessage.server_heartbeat:type_name -> canyonroad.wtp.v1.ServerHeartbeat
	13, // 9: canyonroad.wtp.v1.ServerMessage.goaway:type_name -> canyonroad.wtp.v1.Goaway
	5,  // 10: canyonroad.wtp.v1.ServerMessage.server_update:type_name -> canyonroad.wtp.v1.SessionUpdate
	7,  // 11: canyonroad.wtp.v1.EventBatch.events:type_name -> canyonroad.wtp.v1.CompactEvent
	0,  // 12: canyonroad.wtp.v1.EventBatch.compression:type_name -> canyonroad.wtp.v1.Compression
	8,  // 13: canyonroad.wtp.v1.CompactEvent.integrity:type_name -> canyonroad.wtp.v1.IntegrityRecord
	1,  // 14: canyonroad.wtp.v1.Watchtower.Stream:input_type -> canyonroad.wtp.v1.ClientMessage
	2,  // 15: canyonroad.wtp.v1.Watchtower.Stream:output_type -> canyonroad.wtp.v1.ServerMessage
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_canyonroad_wtp_v1_wtp_proto_init() }
func file_canyonroad_wtp_v1_wtp_proto_init() {
	if File_canyonroad_wtp_v1_wtp_proto != nil {
		return
	}
	file_canyonroad_wtp_v1_wtp_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_SessionInit)(nil),
		(*ClientMessage_SessionUpdate)(nil),
		(*ClientMessage_EventBatch)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_TransportLoss)(nil),
		(*ClientMessage_Shutdown)(nil),
	}
	file_canyonroad_wtp_v1_wtp_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_SessionAck)(nil),
		(*ServerMessage_BatchAck)(nil),
		(*ServerMessage_ServerHeartbeat)(nil),
		(*ServerMessage_Goaway)(nil),
		(*ServerMessage_ServerUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_canyonroad_wtp_v1_wtp_proto_rawDesc), len(file_canyonroad_wtp_v1_wtp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_canyonroad_wtp_v1_wtp_proto_goTypes,
		DependencyIndexes: file_canyonroad_wtp_v1_wtp_proto_depIdxs,
		EnumInfos:         file_canyonroad_wtp_v1_wtp_proto_enumTypes,
		MessageInfos:      file_canyonroad_wtp_v1_wtp_proto_msgTypes,
	}.Build()
	File_canyonroad_wtp_v1_wtp_proto = out.File
	file_canyonroad_wtp_v1_wtp_proto_goTypes = nil
	file_canyonroad_wtp_v1_wtp_proto_depIdxs = nil
}
