// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: agentsh/v1/pty.proto

package ptygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentshPTY_ExecPTY_FullMethodName = "/agentsh.v1.AgentshPTY/ExecPTY"
)

// AgentshPTYClient is the client API for AgentshPTY service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentshPTY provides interactive PTY execution (stdin/stdout bytes, resize, signals).
type AgentshPTYClient interface {
	ExecPTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg], error)
}

type agentshPTYClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentshPTYClient(cc grpc.ClientConnInterface) AgentshPTYClient {
	return &agentshPTYClient{cc}
}

func (c *agentshPTYClient) ExecPTY(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentshPTY_ServiceDesc.Streams[0], AgentshPTY_ExecPTY_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecPTYClientMsg, ExecPTYServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentshPTY_ExecPTYClient = grpc.BidiStreamingClient[ExecPTYClientMsg, ExecPTYServerMsg]

// AgentshPTYServer is the server API for AgentshPTY service.
// All implementations must embed UnimplementedAgentshPTYServer
// for forward compatibility.
//
// AgentshPTY provides interactive PTY execution (stdin/stdout bytes, resize, signals).
type AgentshPTYServer interface {
	ExecPTY(grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]) error
	mustEmbedUnimplementedAgentshPTYServer()
}

// UnimplementedAgentshPTYServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentshPTYServer struct{}

func (UnimplementedAgentshPTYServer) ExecPTY(grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]) error {
	return status.Errorf(codes.Unimplemented, "method ExecPTY not implemented")
}
func (UnimplementedAgentshPTYServer) mustEmbedUnimplementedAgentshPTYServer() {}
func (UnimplementedAgentshPTYServer) testEmbeddedByValue()                    {}

// UnsafeAgentshPTYServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentshPTYServer will
// result in compilation errors.
type UnsafeAgentshPTYServer interface {
	mustEmbedUnimplementedAgentshPTYServer()
}

func RegisterAgentshPTYServer(s grpc.ServiceRegistrar, srv AgentshPTYServer) {
	// If the following call pancis, it indicates UnimplementedAgentshPTYServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentshPTY_ServiceDesc, srv)
}

func _AgentshPTY_ExecPTY_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentshPTYServer).ExecPTY(&grpc.GenericServerStream[ExecPTYClientMsg, ExecPTYServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentshPTY_ExecPTYServer = grpc.BidiStreamingServer[ExecPTYClientMsg, ExecPTYServerMsg]

// AgentshPTY_ServiceDesc is the grpc.ServiceDesc for AgentshPTY service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentshPTY_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentsh.v1.AgentshPTY",
	HandlerType: (*AgentshPTYServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecPTY",
			Handler:       _AgentshPTY_ExecPTY_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentsh/v1/pty.proto",
}
